### ISSUE TITLE
Add option to emit IR and C code

### ISSUE THREAD

**Issue by drewrip** [drewrip/rascal#8]
I came up with a pretty simple IR that I'm hoping to use for both backends. This was in hope of creating an easier representation to translate to the target. It is simple a vector of `IRNode`'s (see [src/ir.rs](https://github.com/drewrip/rascal/blob/423d3a28dd1a52c9215bc6663937fb59ca14bc1f/src/ir.rs#L5)). Basically the idea is that it should be read from top to bottom to produce code even though it also contains a notion of scope. Anyways, that's not super important, but just some background.

What I'd like to do is to add a command line option `--emit` that lets you specify which intermediate representations to dump on the way to the final target. This would be similar to how the Rust `--emit` [flag works](https://doc.rust-lang.org/rustc/command-line-arguments.html#--emit-specifies-the-types-of-output-files-to-generate).

For instance:
```
rascalc fib.ras -o fib --emit=ir
```
should dump a representation of the IR to a file. Or `--emit=ir,C`, should dump both the IR and the C source code. Currently [we always dump](https://github.com/drewrip/rascal/blob/423d3a28dd1a52c9215bc6663937fb59ca14bc1f/src/backends/c.rs#L87) the C source code, however this shouldn't be the default.

In essence we want to be able to serialize the `state.build_stack` [here](https://github.com/drewrip/rascal/blob/423d3a28dd1a52c9215bc6663937fb59ca14bc1f/src/main.rs#L52) (which is a `Vec<IRNode>`) into a `<outfile>.ir` file.

Then after we can produce these representations, we'll want to create the ability to start the compilation directly from the IR file, but thats a follow up for sure.

**Comment by drewrip** [comment]
@THE-COB Let me know if this looks interesting!

**Comment by drewrip** [comment]
Currently the code uses the [Clap](https://docs.rs/clap/latest/clap/) library, so the CLI arguments are represented [here](https://github.com/drewrip/rascal/blob/423d3a28dd1a52c9215bc6663937fb59ca14bc1f/src/main.rs#L20).

**Comment by THE-COB** [comment]
> @THE-COB Let me know if this looks interesting!

This looks excellent

**Comment by drewrip** [comment]
Implemented by #9
